# -*- coding: utf-8 -*-
{
    'name': 'Tamam Hospital',
    'version': '0.2',
    'sequence': 1,
    'author': 'Abdullah.',
    'category': 'uncategorized',
    'summary': 'Tamam Hospital For Royal Treatment',
    'license': 'AGPL-3',
    'description': """

    """,
    'website': 'http://www.tamamhospital.sd',
    'images': ['static/description/icon.png'],
    'depends': ['sale', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/cron.xml',
        'data/mail_template.xml',
        'data/sequence.xml',
        'wizard/create_appointments.xml',
        'view/patient.xml',
        'view/appointment.xml',
        'view/doctor.xml',
        'view/lab.xml',
        'view/settings.xml',
        'view/template.xml',
        'view/dashboard.xml',
        'view/sale_order.xml',
        'view/server_action.xml',
        'view/website_form.xml',
        'reports/patients_cards.xml',
        'reports/appointments.xml',
        'reports/sale_report_inherit.xml',
    ],
    'qweb': [
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}